[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.2", features = ["full"] }
serde_json = "1.0.127"
eyre = "0.6.8"
tokio = { version = "1.17.0", features = ["full"] }